### ISSUE TITLE
NAIS.py 中 n的指数α应为负数

### ISSUE THREAD

**Issue by molybdenumyz** [AaronHeee/Neural-Attentive-Item-Similarity-Model#6]
第145行应修正为
`self.coeff = tf.pow(self.num_idx, -tf.constant(self.alpha, tf.float32, [1]))`

**Comment by AaronHeee** [comment]
Thanks to point out that, we will correct our implementation ASAP. Thanks to the setting of alpha=0, our experiments are still valid and thanks for your issue again.
